// SPDX-FileCopyrightText: Copyright (c) 2026 The llingr-rs-kafka Authors
// SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-Llingr-Commercial

//! Mirrors the fenced `rust` code samples from README.md and docs/*.md into a
//! single generated markdown file in OUT_DIR. src/lib.rs attaches that file as
//! crate docs, so `cargo test --doc` compiles every sample as a doctest.
//!
//! Two deliberate choices make this a COMPILE check rather than a run:
//!   - Only blocks whose info string's first token is `rust` are mirrored, so
//!     prose fences (unlabelled, ```sh, ```text, ```dockerfile, JSON, output)
//!     are never handed to the compiler.
//!   - Every mirrored block is re-tagged `no_run` (unless it was `ignore` or
//!     `compile_fail`), so `cargo test --doc` compiles it but never executes
//!     it: the samples call the blocking `engine.run()` against a broker, so
//!     running them is wrong and compiling them is the point. (`cargo test
//!     --doc --no-run` is rejected by cargo, hence `no_run` per block.)
//!
//! Hidden setup lines (the rustdoc `# ` convention already used in the pages)
//! and the implicit-main wrapping are handled by rustdoc itself, because the
//! mirrored blocks stay markdown doctests rather than being re-wrapped by hand.

use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    let manifest = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let repo = manifest
        .parent()
        .expect("docs-examples/ must sit directly under the repository root")
        .to_path_buf();

    // Sources: README.md and the top-level docs/*.md pages. docs/internal/ is
    // deliberately excluded: contributor notes may contain illustrative
    // snippets that are not meant to compile.
    let mut sources: Vec<PathBuf> = Vec::new();
    let readme = repo.join("README.md");
    if readme.is_file() {
        sources.push(readme);
    }
    let docs_dir = repo.join("docs");
    if docs_dir.is_dir() {
        let mut pages: Vec<PathBuf> = fs::read_dir(&docs_dir)
            .expect("read docs/")
            .flatten()
            .map(|entry| entry.path())
            .filter(|path| path.extension().map(|ext| ext == "md").unwrap_or(false))
            .collect();
        pages.sort();
        sources.extend(pages);
    }

    let mut out =
        String::from("<!-- GENERATED by docs-examples/build.rs from README.md and docs/*.md. Do not edit. -->\n\n");
    for src in &sources {
        let text = fs::read_to_string(src).unwrap_or_default();
        let blocks = extract_rust_blocks(&text);
        if !blocks.is_empty() {
            let rel = src.strip_prefix(&repo).unwrap_or(src);
            // A markdown heading (rustdoc ignores it) so a failing doctest's
            // location in samples.md maps back to the source page.
            out.push_str(&format!("## {}\n\n", rel.display()));
            for (info, body) in blocks {
                out.push_str("```");
                out.push_str(&reemit_info(&info));
                out.push('\n');
                out.push_str(&body);
                if !body.ends_with('\n') {
                    out.push('\n');
                }
                out.push_str("```\n\n");
            }
        }
        println!("cargo:rerun-if-changed={}", src.display());
    }
    // Re-run when a page is added to or removed from docs/.
    println!("cargo:rerun-if-changed={}", docs_dir.display());

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    fs::write(out_dir.join("samples.md"), out).expect("write samples.md");
}

/// Returns `(info_string, body)` for every fenced block whose info string's
/// first token is `rust`. Fences are matched after trimming leading whitespace;
/// nested fences are not expected in these pages.
fn extract_rust_blocks(text: &str) -> Vec<(String, String)> {
    let mut blocks = Vec::new();
    let mut in_block = false;
    let mut info = String::new();
    let mut body = String::new();
    for line in text.lines() {
        let trimmed = line.trim_start();
        if !in_block {
            if let Some(rest) = trimmed.strip_prefix("```") {
                in_block = true;
                info = rest.trim().to_string();
                body.clear();
            }
        } else if trimmed.starts_with("```") {
            in_block = false;
            let first = info
                .split(|c| c == ',' || c == ' ' || c == '\t')
                .next()
                .unwrap_or("");
            if first == "rust" {
                blocks.push((info.clone(), body.clone()));
            }
            info.clear();
            body.clear();
        } else {
            body.push_str(line);
            body.push('\n');
        }
    }
    blocks
}

/// Re-tags a mirrored `rust` block for compile-only checking: `ignore` and
/// `compile_fail` semantics are preserved; everything else becomes `no_run` so
/// it compiles but never executes.
fn reemit_info(info: &str) -> String {
    let attrs: Vec<&str> = info
        .split(',')
        .map(|attr| attr.trim())
        .filter(|attr| !attr.is_empty())
        .collect();
    if attrs.iter().any(|attr| *attr == "ignore") {
        return "rust,ignore".to_string();
    }
    if attrs.iter().any(|attr| *attr == "compile_fail") {
        return "rust,compile_fail".to_string();
    }
    "rust,no_run".to_string()
}
